model:
  policy_ckpt: 'logs_diffusion/training_2024_01_22__19_57_5/checkpoints/131000.pt'   # retrained targetdiff
  value_ckpt: 'logs_diffusion/training_2024_01_22__19_57_5/checkpoints/131000.pt'
  joint_ckpt: 'logs_diffusion/training_2024_01_22__19_57_5/checkpoints/131000.pt'   # KGDiffDock(ˆh0)
 



sample:
  seed: 2026
  num_samples: 40
  num_steps: 5000
  pos_only: False
  center_pos_mode: protein
  sample_num_atoms: ref #prior


